# cocogitto - https://docs.cocogitto.io/

# 标签前缀
tag_prefix = 'v'

# 仅检查最新标签后的提交
from_latest_tag = true

# 忽略合并提交
ignore_merge_commits = true

# 发版前钩子
pre_bump_hooks = [
  # 写版本清单
  'echo {".": "{{version}}"} > .release-please-manifest.json',
]

# 提交类型（对齐 Conventional Commits，默认类型集）
[commit_types]

# 更新日志
[changelog]
# 路径
path = 'CHANGELOG.md'
# 远程
remote = 'github.com'
# 所有者
owner = 'sweets-wtt'
# 仓库名
repository = 'application'
