# mise - https://mise.jdx.dev/

# 设置
[settings]
# 锁文件
lockfile = true
# 严格锁定
locked = true
# 自动安装
auto_install = false
# 缺失自动安装
not_found_auto_install = false
# 系统回退
not_found_system_fallback = false

# 工具（命令： `mise use <tool>@<version>` ）
[tools]
# 构建系统
"aqua:moonrepo/moon" = "2.5.4"
# 拼写检查
"aqua:crate-ci/typos" = "1.50.1"
# 代码格式化
"aqua:oxc-project/oxc/oxfmt" = "1.82.0"
# 正则搜索
"aqua:BurntSushi/ripgrep" = "15.2.0"
# 提交检查
"aqua:cocogitto/cocogitto" = "7.0.0"
# 工作流审计
"aqua:zizmorcore/zizmor" = "1.30.0"
# 链接检查
"aqua:lycheeverse/lychee" = "0.24.2"
# 语法检查
"aqua:rhysd/actionlint" = "1.7.12"
# 密钥扫描
"aqua:gitleaks/gitleaks" = "8.30.1"
# 漏洞扫描
"aqua:aquasecurity/trivy" = "0.74.0"
# 配置校验
"aqua:Boeing/config-file-validator" = "2.3.0"
# 密钥加密
"aqua:getsops/sops" = "3.13.3"
# 加密工具
"aqua:FiloSottile/age" = "1.3.2"
# 契约检查
"aqua:daveshanley/vacuum" = "0.30.3"
# 兼容检查
"github:tufin/oasdiff" = "v1.31.0"
# HTTP 测试
"aqua:Orange-OpenSource/hurl" = "8.0.1"
# Python 运行时
python = "3.12.14"
# 依赖管理
"aqua:astral-sh/uv" = "0.12.10"
# 代码检查
"aqua:astral-sh/ruff" = "0.16.6"
# 类型检查
"aqua:astral-sh/ty" = "0.0.78"
# JavaScript 运行时
node = "26.8.1"
# 包管理
bun = "1.4.2"
# 代码检查
"aqua:oxc-project/oxc/oxlint" = "1.82.0"
