# mise - `https://mise.jdx.dev/`

# === 设置 ===
[settings]
auto_install = false
locked = true
lockfile = true

# === 工具 ===
[tools]
cocogitto = "latest"
dprint = "latest"
lefthook = "latest"
typos = "latest"
vacuum = "latest"

# === 任务 ===
[tasks.list]
description = "列出任务"
run = [
  "mise tasks ls",
]

[tasks.lock]
description = "锁定版本"
run = [
  "mise lock",
]

[tasks.install]
description = "安装工具"
depends = ["lock"]
run = [
  "mise install --locked",
]

[tasks.upgrade]
description = "更新版本"
run = [
  "mise upgrade",
  "mise lock --bump",
  "mise install --locked",
]

[tasks.lint]
description = "代码检查"
run = [
  "dprint check",
  "typos",
]

[tasks.format]
description = "代码格式化"
run = [
  "dprint fmt",
]

[tasks.contracts]
description = "检查契约"
run = [
  "vacuum lint --ruleset contracts/http/vacuum.yaml contracts/http/openapi.yaml",
]
