/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * HTTP 契约
 * OpenAPI spec version: 0.1.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { Healthz200 } from "../../schemas";

export const getHealthzResponseMock = (): Healthz200 => ({
  ...{
    code: faker.number.int(),
    message: faker.string.alpha({ length: { min: 10, max: 20 } }),
    data: {},
  },
  ...{ data: { status: faker.string.alpha({ length: { min: 10, max: 20 } }) } },
});

export const getHealthzMockHandler = (
  overrideResponse?:
    | Healthz200
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Healthz200> | Healthz200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/healthz",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getHealthzResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getDefaultMock = () => [getHealthzMockHandler()];
