/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * HTTP 契约
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { unref } from "vue";

import type { Healthz200 } from "../../schemas";

import { appFetch } from "../../../client";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type healthzResponse200 = {
  data: Healthz200;
  status: 200;
};

export type healthzResponseSuccess = healthzResponse200 & {
  headers: Headers;
};

export type healthzResponse = healthzResponseSuccess;

export const getHealthzUrl = () => {
  return `/healthz`;
};

export const healthz = async (
  options?: Parameters<typeof appFetch>[1],
): Promise<healthzResponse> => {
  return appFetch<healthzResponse>(getHealthzUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthzQueryKey = () => {
  return ["healthz"] as const;
};

export const getHealthzQueryOptions = <
  TData = Awaited<ReturnType<typeof healthz>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>>;
  request?: SecondParameter<typeof appFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getHealthzQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthz>>> = ({ signal }) =>
    healthz({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthz>>,
    TError,
    TData
  >;
};

export type HealthzQueryResult = NonNullable<Awaited<ReturnType<typeof healthz>>>;
export type HealthzQueryError = unknown;

export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>>;
    request?: SecondParameter<typeof appFetch>;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthzQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}
