# PostgreSQL 客户端认证 - https://www.postgresql.org/docs/current/auth-pg-hba-conf.html

# 类型      数据库        用户        地址          方法

# 本地 Unix 套接字（容器内健康检查与初始化）
local       all           all                       trust
# 内网主机连接（SCRAM 口令）
host        all           all         0.0.0.0/0     scram-sha-256
host        all           all         ::/0          scram-sha-256
