# PostgreSQL 运行时配置 - `https://www.postgresql.org/docs/current/runtime-config.html`

# 监听地址
listen_addresses = '*'
# 最大连接数
max_connections = 100
# 口令加密
password_encryption = 'scram-sha-256'
# SSL
ssl = off

# 记录连接
log_connections = on
# 记录断开
log_disconnections = on
# 行前缀
log_line_prefix = '%m [%p] %q%u@%d '

# 时区
timezone = 'UTC'
