# Docker Compose - `https://docs.docker.com/compose/`

# 项目名
name: application

# 引入
include:
  # PostgreSQL
  - "postgresql/compose.yaml"
  # PgBouncer
  - "pgbouncer/compose.yaml"
  # Valkey
  - "valkey/compose.yaml"
  # Garage
  - "garage/compose.yaml"
  # Hatchet
  - "hatchet/compose.yaml"
  # authentik
  - "authentik/compose.yaml"
  # OpenObserve
  - "observe/compose.yaml"
  # Traefik
  - "traefik/compose.yaml"
  # Server
  - "../apps/server/compose.yaml"

# 命名网络
networks:
  # 入口网
  edge:
  # 应用内部网
  app-internal:
  # 数据内部网
  data-internal:
  # 管理网
  management:
    # 外部隔离
    internal: true
  # 出站网
  egress:

# 命名卷
volumes:
  # PostgreSQL 数据
  postgresql-data:
  # PostgreSQL 仓库
  postgresql-repo:
  # Valkey 数据
  valkey-data:
  # Garage 数据
  garage-data:
  # Garage 仓库
  garage-repo:
  # Hatchet 配置
  hatchet-config:
  # authentik 数据
  authentik-data:
  # OpenObserve 数据
  openobserve-data:
  # Collector 存储
  collector-storage:
  # Traefik 证书
  traefik-acme:

# 密钥
secrets:
  # PostgreSQL
  postgres:
    # 环境变量
    environment: POSTGRES_PASSWORD
  # Hatchet 主密钥集
  hatchet-master-keyset:
    # 环境变量
    environment: HATCHET_MASTER_KEYSET
  # Hatchet JWT 公钥集
  hatchet-jwt-public-keyset:
    # 环境变量
    environment: HATCHET_JWT_PUBLIC_KEYSET
  # Hatchet JWT 私钥集
  hatchet-jwt-private-keyset:
    # 环境变量
    environment: HATCHET_JWT_PRIVATE_KEYSET
