# moon 工作区 - https://moonrepo.dev/docs/config/workspace

# 项目
projects:
  # 标识格式
  globFormat: 'source-path'
  # 匹配模式
  globs:
    - '**/moon.yaml'
  # 映射
  sources:
    # 根项目
    root: '.'

# 版本控制
vcs:
  # 客户端
  client: 'git'
  # 默认分支
  defaultBranch: 'main'
  # 钩子
  hooks:
    # 提交前
    pre-commit:
      - 'mise exec -- moon run :lint'
    # 提交信息
    commit-msg:
      - 'mise exec -- cog verify --file $ARG1'

# 管道
pipeline:
  # 安装依赖
  installDependencies: false
