# Docker Compose - `https://docs.docker.com/compose/`

# 服务
services:
  # PgBouncer
  pgbouncer:
    image: "edoburu/pgbouncer@sha256:7d7a27d9e90985cab5cf42256f5c13a3120baa4b055b69df37beb272b89b2340"
    restart: unless-stopped
    environment:
      # 口令派生用户
      DB_USER: postgres
      # 口令
      DB_PASSWORD: "${POSTGRES_PASSWORD:?}"
      # 认证方式
      AUTH_TYPE: "scram-sha-256"
    volumes:
      # 配置文件
      - "./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro"
    # 健康检查
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432"]
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "30s"
    networks:
      # 数据内部网
      - "data-internal"
    depends_on:
      postgresql:
        condition: "service_healthy"
