/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * HTTP 契约
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

export const Healthz200 = zod
  .object({
    code: zod.int(),
    message: zod.string(),
    data: zod.looseObject({}),
  })
  .and(
    zod.object({
      data: zod.object({
        status: zod.string(),
      }),
    }),
  );

export type Healthz200 = zod.input<typeof Healthz200>;
export type Healthz200Output = zod.output<typeof Healthz200>;
