/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API
 * HTTP 契约
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

export const Response = zod.object({
  code: zod.int(),
  message: zod.string(),
  data: zod.looseObject({}),
});

export type Response = zod.input<typeof Response>;
export type ResponseOutput = zod.output<typeof Response>;
