# GitHub Actions 持续集成 - https://docs.github.com/actions

# 工作流名称
name: ci

# 触发事件
on:
  pull_request:
  push:
    branches:
      - main

# 令牌权限
permissions:
  contents: read

# 作业
jobs:
  # 代码检查
  lint:
    runs-on: ubuntu-latest
    steps:
      # 检出仓库
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      # 环境管理
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
        with:
          version: "2026.8.14"
      # 代码检查
      - run: moon run :lint
        env:
          CI: ""

  # 任务编排
  moon:
    runs-on: ubuntu-latest
    steps:
      # 检出仓库
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      # 环境管理
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
        with:
          version: "2026.8.14"
      # 提交检查
      - run: cog check
      # 构建与测试
      - run: moon ci
